name: Build With CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - name: Configure
       run: cmake
     - name: Make
       run: make
